name: API Tests

on:
  push:
    branches: [ api-tests ]
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest allure-pytest

      - name: Remove UI conftest (to avoid playwright import)
        run: rm -f conftest.py

      - name: Run API tests
        run: pytest API_tests/test_basic_auth_api.py -v --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-api
          path: allure-results
          retention-days: 7
